version: '3.8'

services:
    app:
        container_name: nestjs_app
        image: nestjs_app:1.0.0
        build:
            context: .
            dockerfile: ./Dockerfile
        command: npm run start:prod
        ports:
            - 3000:3000

